// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: openAccount.sql

package db

import (
	"context"
)

const openAccount = `-- name: openAccount :one
INSERT INTO accounts (
    owner, 
    balance,
    currency
) VALUES (
    $1, $2, $3
) RETURNING id, owner, balance, currency, created_at
`

type openAccountParams struct {
	Owner    string `json:"owner"`
	Balance  string `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) openAccount(ctx context.Context, arg openAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.openAccountStmt, openAccount, arg.Owner, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
